### ISSUE TITLE
Unexpected checkstyle errors when upgrading plugin

### ISSUE THREAD

**Issue by vandac** [kaminomobile/soter#2]
Dear Kamino,

I tried upgrading our project from using the old dlabs project and I am now seeing new checkstyle errors.

The original setup we had:
`    dependencies {
        classpath 'gradle.plugin.si.dlabs.gradle:soter:1.0.2'
...
    // Static code rules
    checkstyleRules "si.dlabs.check:checkstyle:0.3@xml"
    findbugsRules "si.dlabs.check:findbugs:0.1@xml"
    pmdRules "si.dlabs.check:pmd:0.1@xml"
...

soter {

    checkstyle {
        enabled true
    }

    findbugs {
        enabled true
        reportLevel "high"
    }

    pmd {
        enabled true
    }

}

`

after upgrading, we are referencing the plugin as follows:

`    dependencies {
        classpath 'gradle.plugin.si.kamino.gradle:soter:2.1.1'
..
apply plugin: 'si.kamino.soter'
..
`
and the same config for rules. the rules are in our artifactory.

After upgrading, I am getting new errors in checkstyle, such as:
`message="&apos;,&apos; is preceded with whitespace." source="com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceBeforeCheck"/>`
`message="Redundant &apos;public&apos; modifier." source="com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck"/>`
`message="&apos;{&apos; at column 17 should be on the previous line." source="com.puppycrawl.tools.checkstyle.checks.blocks.LeftCurlyCheck"/>`
but we do not have such rules and I'd like to avoid using rules we do not want to use.

How can I achieve this?

**Comment by blazsolar** [comment]
Errors that you se are do to update of checkstyle plugin. Latest version of plugin uses version 6.7 of checkstyle that adds those check by default. 

You have few options here. 
1. You can fix issues mentioned above in your code :)
2. You can modify your `checkstyle.xml` file to ignore those checks or threat them as warnings. 
3. You can tell soter to use older checkstyle version, that does not yet include these checks, thourgh DSL.

```
soter {
    checkstyle {
        toolVersion "<older_version_to_use>"
    }
}
```
Hope this helps. Ping me if you need any extra help. 
I'm closing this issue because it is not an soter issue.
